-- Enable Row Level Security
alter default privileges revoke execute on functions from public;

-- CARS TABLE
create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text default 'Sedan',
  capacity int default 4,
  description text,
  images text[] default '{}',
  features text[] default '{}',
  price_per_km numeric,
  is_active boolean default true
);

-- TOURS TABLE
create table if not exists public.tours (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  destination text,
  duration text,
  description text,
  image text,
  highlights text[] default '{}',
  price numeric,
  is_active boolean default true
);

-- BOOKINGS TABLE
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_phone text not null,
  pickup_location text,
  drop_location text,
  travel_date date,
  travel_time time,
  booking_type text check (booking_type in ('car', 'tour', 'cab')),
  status text default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  special_requests text
);

-- RLS POLICIES
alter table public.cars enable row level security;
alter table public.tours enable row level security;
alter table public.bookings enable row level security;

-- POLICIES
create policy "Public cars are viewable by everyone" on public.cars for select using (true);
create policy "Public tours are viewable by everyone" on public.tours for select using (true);
create policy "Anyone can create a booking" on public.bookings for insert with check (true);
create policy "Admins can manage cars" on public.cars using (auth.role() = 'authenticated');
create policy "Admins can manage tours" on public.tours using (auth.role() = 'authenticated');
create policy "Admins can manage bookings" on public.bookings using (auth.role() = 'authenticated');
